In [2]:
a = [[1] * (i + 1) for i in range(5)]

In [3]:
a

[[1], [1, 1], [1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1, 1]]

In [5]:
for i in range(len(a)):
    for j in range(1,i):
        print(i, j)

2 1
3 1
3 2
4 1
4 2
4 3


In [6]:
i = 2
j = 1


In [7]:
a[i-1]

[1, 1]

In [8]:
a[i - 1][j-1]

1

In [9]:
import numpy as np

In [10]:
np

<module 'numpy' from '/home/simsol/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'>

In [11]:
a = np.arange(4*4).reshape(4,4)

In [12]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
for i in range(len(a)):
    
    _a = [a[j][i] for j in range(len(a))]
    print(_a)

[0, 4, 8, 12]
[1, 5, 9, 13]
[2, 6, 10, 14]
[3, 7, 11, 15]


In [14]:
_a

[4, 5, 6, 7]

In [19]:
len(a) // 2

2

In [22]:
(np.arange(7*7).reshape(7,7))

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [23]:
import math

In [25]:
int(math.sqrt(4))

2

In [27]:
int(math.sqrt(7))

2

In [28]:
int(math.sqrt(9))

3

In [31]:
arr = (np.arange(9*9).reshape(9,9))

In [32]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [35]:
region = int(math.sqrt(len(arr)))

In [36]:
region


3

In [43]:
region_arr = []
for i in range(region):
    for j in range(region):
#         l = []
#         for b in range(i * region, (i+1) * region):
#             for a in range(j * region, (j + 1) * region):
#                 l.append(arr[b][a])
        
        
#         region_arr.append(l)
            
        
        region_arr.append(
            [arr[b][a] for b in range(i * region, (i+1) * region) for a in range(j* region, (j+1) * region)]
        )

In [44]:
region_arr

[[0, 1, 2, 9, 10, 11, 18, 19, 20],
 [3, 4, 5, 12, 13, 14, 21, 22, 23],
 [6, 7, 8, 15, 16, 17, 24, 25, 26],
 [27, 28, 29, 36, 37, 38, 45, 46, 47],
 [30, 31, 32, 39, 40, 41, 48, 49, 50],
 [33, 34, 35, 42, 43, 44, 51, 52, 53],
 [54, 55, 56, 63, 64, 65, 72, 73, 74],
 [57, 58, 59, 66, 67, 68, 75, 76, 77],
 [60, 61, 62, 69, 70, 71, 78, 79, 80]]

In [39]:
region_arr[0]

[0, 1, 2, 9, 10, 11, 18, 19, 20]

In [40]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [45]:
math.sqrt(1)

1.0