In [1]:
import numpy as np

In [81]:
arr = np.arange(3*3).reshape(3,3)

In [66]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
arr = arr.tolist()

In [84]:
a = []
for i in range(3):
    b = []
    for j in range(3):
#         b.append(arr[j][i])
#         print( arr[j][i], end=" ")
#         arr[i][j], arr[j][i] = arr[j][i], arr[i][j]
        arr[[i],j] = arr[[j],i],arr[[i],j]
#         col = arr[i]
#         col_val = col[j]
#         arr[[i,j]], arr[[j,i]] = arr[[j,i]], arr[[i,j]]
        
#     for i in range()
    a.append(b)    
    print()

In [85]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [72]:
a

[[0, 3, 6], [1, 4, 7], [2, 5, 8]]

In [8]:
arr[0][1] = 5

In [54]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [56]:
arr[0][1], arr[1][0] = arr[1][0], arr[0][1]

In [57]:
arr

array([[0, 3, 2],
       [1, 4, 5],
       [6, 7, 8]])

In [73]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [102]:
arr[[0],1], arr[[1],1] = arr[[1],0].copy(), arr[[0],1].copy() 

In [103]:
arr

array([[0, 3, 2],
       [3, 1, 5],
       [6, 7, 8]])

In [89]:
arr

array([[0, 4, 2],
       [3, 1, 5],
       [6, 7, 8]])