In [1]:
import numpy as np

In [2]:
arr = np.arange(9).reshape(3,3)

In [3]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
sp = []
offset = 0

In [5]:
offset == len(arr) - offset - 1

False

In [6]:
arr[offset][offset:-1-offset]

array([0, 1])

In [7]:
list(zip(*arr))

[(0, 3, 6), (1, 4, 7), (2, 5, 8)]

In [8]:
list(zip(*arr))[-offset - 1][offset : -1 - offset ]

(2, 5)

In [9]:
arr[-offset - 1][-1 - offset : offset : -1]

array([8, 7])

In [10]:
ar1 = np.arange(6*6).reshape(6, 6
                            )

In [11]:
ar1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [12]:
j = 4
l = []
for i in range(len(ar1)):
    l.append(ar1[i][j])

In [13]:
offset = 1

In [14]:
l[offset: len(ar1) - offset - 1]

[10, 16, 22]

In [15]:
l

[4, 10, 16, 22, 28, 34]

In [16]:
1 == 3 -1-1

True

In [17]:
(6 + 1) // 2 

3

In [18]:
ar1[0][3: -2]

array([3])

In [19]:
b = ar1[-1 -offset]

In [20]:
b

array([24, 25, 26, 27, 28, 29])

In [21]:
b[-1:-3:-1]

array([29, 28])

In [22]:
d = 0

In [23]:
d = (d + 1) &3

In [24]:
d

1

In [25]:
bin(4)

'0b100'

In [26]:
bin(3)

'0b11'

In [27]:
ar1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [28]:
ar1[~1]

array([24, 25, 26, 27, 28, 29])

In [43]:
~0

-1

In [42]:
5 //2

2

In [34]:
bin(~3)

'-0b100'

In [35]:
not 3

False

In [36]:
~3

-4

In [37]:
~ -5

4

In [38]:
~ -5

4

In [39]:
bin(5)

'0b101'

In [40]:
bin(4)

'0b100'

In [41]:
bin(-5-1)

'-0b110'